using YARG.Settings;
using YARG.Localization;

namespace YARG.Settings.Types
{
    /// <summary>
    /// Dropdown that acts as a menu of independent on/off toggles. Each item
    /// carries a state glyph regenerated by <see cref="ValueToString"/> on
    /// every visual refresh. The setting's value is the sentinel
    /// <see cref="PV_HEADER"/>, which is not in the option list — so the
    /// TMP_Dropdown sits at index -1 showing its placeholder as a fixed
    /// caption, and picking any item always changes the index (TMP suppresses
    /// onValueChanged when the index doesn't change). The OnChange handler in
    /// BuildPreviewControls snaps the value back to the sentinel after each
    /// pick.
    /// </summary>
    public class PreviewVisualsDropdownSetting : DropdownSetting<string>
    {
        public const  string PV_HEADER            = "Preview Options";
        public const  string PV_STAR_POWER_NOTES  = "Star Power Notes";
        public const  string PV_STAR_POWER_ACTIVE = "Star Power Active";
        public const  string PV_GROOVE            = "Groove";
        public const  string PV_LEFTY_FLIP        = "Lefty Flip";
        private const string PV_GLYPH_ON          = "\u2611 "; // ☑ ballot box with check
        private const string PV_GLYPH_OFF         = "\u2610 "; // ☐ ballot box

        // Localization keys for the preview-toggle labels and caption. The PV_*
        // values above are the dropdown's internal option values (stable
        // sentinels for the OnChange switch); these keys map them to localized
        // display text via ValueToString.
        public const  string PV_KEY_VISUALS           = "Settings.PresetSetting.PreviewVisuals.Visuals.Name";
        private const string PV_KEY_STAR_POWER_NOTES  = "Settings.PresetSetting.PreviewVisuals.StarPowerNotes.Name";
        private const string PV_KEY_STAR_POWER_ACTIVE = "Settings.PresetSetting.PreviewVisuals.StarPowerActive.Name";
        private const string PV_KEY_GROOVE            = "Settings.PresetSetting.PreviewVisuals.Groove.Name";
        private const string PV_KEY_LEFTY_FLIP        = "Settings.PresetSetting.PreviewVisuals.LeftyFlip.Name";

        public PreviewVisualsDropdownSetting() : base(PV_HEADER, null, localizable: false)
        {
        }

        public override string ValueToString(string value)
        {
            bool on;
            string key;
            switch (value)
            {
                case PV_STAR_POWER_NOTES:
                    on = SettingsManager.PreviewOptions.ForceStarPowerNotes;
                    key = PV_KEY_STAR_POWER_NOTES;
                    break;
                case PV_STAR_POWER_ACTIVE:
                    on = SettingsManager.PreviewOptions.ForceStarPower;
                    key = PV_KEY_STAR_POWER_ACTIVE;
                    break;
                case PV_GROOVE:
                    on = SettingsManager.PreviewOptions.ForceGroove;
                    key = PV_KEY_GROOVE;
                    break;
                case PV_LEFTY_FLIP:
                    on = SettingsManager.PreviewOptions.LeftyFlip;
                    key = PV_KEY_LEFTY_FLIP;
                    break;
                default:
                    return value;
            }

            return (on ? PV_GLYPH_ON : PV_GLYPH_OFF) + Localize.Key(key);
        }
    }
}